-- ============================================================================
-- 롤러코스터 타이쿤 수학 퀴즈 - Supabase 데이터베이스 스키마 (schema.sql)
-- Supabase Dashboard -> SQL Editor 에 이 쿼리를 복사하여 실행하세요.
-- ============================================================================

-- 1. 학생 게임 저장 데이터 테이블 (game_saves)
CREATE TABLE IF NOT EXISTS public.game_saves (
    nickname TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    game_data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security (RLS) 활성화
ALTER TABLE public.game_saves ENABLE ROW LEVEL SECURITY;

-- 모든 사용자 읽기/쓰기 허용 정책 (익명 클라이언트 지원)
CREATE POLICY "Allow public read access on game_saves" 
    ON public.game_saves FOR SELECT USING (true);

CREATE POLICY "Allow public insert/update access on game_saves" 
    ON public.game_saves FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update access on game_saves" 
    ON public.game_saves FOR UPDATE USING (true);


-- 2. 수학 퀴즈 문제 데이터 테이블 (quiz_questions)
CREATE TABLE IF NOT EXISTS public.quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'choice', -- 'choice' (객관식) 또는 'short' (주관식)
    question TEXT NOT NULL,
    options JSONB DEFAULT '[]'::jsonb, -- 객관식 옵션 배열
    answer TEXT NOT NULL,
    explanation TEXT,
    hint TEXT,
    is_custom BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS 활성화
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on quiz_questions" 
    ON public.quiz_questions FOR SELECT USING (true);

CREATE POLICY "Allow public insert access on quiz_questions" 
    ON public.quiz_questions FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public delete access on quiz_questions" 
    ON public.quiz_questions FOR DELETE USING (true);


-- 3. 초기 시드 데이터 (3학년 1학기 5단원 길이와 시간)
INSERT INTO public.quiz_questions (unit, type, question, options, answer, explanation, hint, is_custom) VALUES
('3학년 1학기 5단원 길이와 시간', 'choice', '1cm를 10칸으로 똑같이 나눈 눈금 한 칸의 길이를 무엇이라고 하나요?', '["1 mm", "1 m", "1 km", "10 mm"]'::jsonb, '1 mm', '1cm를 10칸으로 똑같이 나눈 눈금 한 칸의 길이는 1mm(밀리미터)입니다.', 'cm 다음으로 작은 단위를 생각해보세요.', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '5cm 3mm는 몇 mm일까요?', '["53 mm", "35 mm", "503 mm", "8 mm"]'::jsonb, '53 mm', '1cm는 10mm입니다. 5cm는 50mm이므로, 50mm + 3mm = 53mm입니다.', '1cm = 10mm입니다.', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '1000m를 하나로 묶어서 나타내는 단위는 무엇일까요?', '["1 km", "10 km", "100 cm", "10 mm"]'::jsonb, '1 km', '1000m는 1km(킬로미터)라고 씁니다.', '아주 먼 거리를 나타내는 단위입니다.', false),
('3학년 1학기 5단원 길이와 시간', 'short', '2km 400m는 몇 m일까요? (숫자만 입력 가능)', '[]'::jsonb, '2400', '1km는 1000m입니다. 2km는 2000m이므로 2400m입니다.', '1km = 1000m', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '3500m는 몇 km 몇 m일까요?', '["3km 500m", "35km", "3km 50m", "5km 300m"]'::jsonb, '3km 500m', '3000m는 3km이므로, 3500m는 3km 500m입니다.', '1000m마다 1km입니다.', false),
('3학년 1학기 5단원 길이와 시간', 'short', '시계의 초침이 한 바퀴를 도는 시간인 ''1분''은 몇 초일까요?', '[]'::jsonb, '60초', '초침이 시계를 한 바퀴 도는 데 걸리는 시간은 60초입니다.', '60초 = 1분', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '80초는 몇 분 몇 초일까요?', '["1분 20초", "1분 0초", "2분 20초", "8분"]'::jsonb, '1분 20초', '80초에서 60초(1분)를 빼면 20초가 남으므로 1분 20초입니다.', '80 - 60 = 20', false),
('3학년 1학기 5단원 길이와 시간', 'short', '1분 30초는 모두 몇 초일까요?', '[]'::jsonb, '90초', '1분은 60초입니다. 60초 + 30초 = 90초입니다.', '60 + 30', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '시간의 덧셈을 해봅시다. 2시간 10분 + 1시간 20분은?', '["3시간 30분", "3시간 10분", "4시간 30분", "2시간 30분"]'::jsonb, '3시간 30분', '2+1=3시간, 10+20=30분입니다.', '시간은 시간끼리, 분은 분끼리 더합니다.', false),
('3학년 1학기 5단원 길이와 시간', 'choice', '30분 40초 + 10분 30초는 얼마일까요?', '["41분 10초", "40분 70초", "41분 30초", "40분 10초"]'::jsonb, '41분 10초', '40초+30초=70초(1분 10초)입니다. 따라서 41분 10초가 됩니다.', '60초가 넘으면 1분 받아올림 합니다.', false);
